<?php
/**
 * Top menu for store
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>
<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
$helper = Mage::helper('xmllinks');
?>
<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<?php 
$route = Mage::app()->getRequest()->getRouteName();
$id = Mage::getSingleton('cms/page')->getIdentifier();
?>
<?php if($_menu): ?>
<div class="nav-container">
<div class="nav_container_inner">	
    <ul id="nav">
		<?php if($helper->getConfig('home_active', 'catalog_navigation')):
			$homeLabel = $helper->getConfig('home_label', 'catalog_navigation', 'Home');
			$isHomeActive = trim($this->helper('core/url')->getCurrentUrl(), '/') == trim(Mage::getUrl(), '/') ? ' active' : null;
			?>
		<li class="first<?php echo $isHomeActive; ?>">
			<a href="<?php echo Mage::getUrl(); ?>" class="">
				<span><?php echo $homeLabel; ?></span>
			</a>
		</li>
		<?php endif; ?>
        <?php //echo $_menu ?>
	
	<li class="level0 nav-1 level-top parent <?php if($route == 'cms' && $id == 'photo-wallpaper') { ?> active <?php } ?>">
		<a href="<?php echo Mage::getBaseUrl(); ?>photo-wallpaper" class="level-top">
			<span><?php echo $this->__('Photo Wallpaper') ?></span>
		</a>
	</li>
	<li class="level0 nav-1 level-top parent <?php if($route == 'cms' && $id == 'examples') { ?> active <?php } ?>">
		<a href="<?php echo Mage::getBaseUrl(); ?>examples" class="level-top">
			<span><?php echo $this->__('Examples') ?></span>
		</a>
	</li>	
	<?php $idea_page  = Mage::getBaseUrl()."blog/category/ideas/"; $isIdeaPage="0";?>
	<li class="level0 nav-2 level-top parent <?php if($idea_page == $this->helper('core/url')->getCurrentUrl()) { ?> active <?php $isIdeaPage="1"; } ?>">
		<a href="<?php echo Mage::getBaseUrl(); ?>blog/category/ideas/" class="level-top">
			<span><?php echo $this->__('Ideas'); ?></span>
		</a>
	</li>
	<li class="level0 nav-2 level-top parent <?php if($route == 'cms' && $id == 'installation') { ?> active <?php } ?>">
		<a href="<?php echo Mage::getBaseUrl(); ?>installation" class="level-top">
			<span><?php echo $this->__('Installation'); ?></span>
		</a>
	</li>
	<li class="level0 nav-2 level-top parent <?php if($route == 'cms' && $id == 'commercial') { ?> active <?php } ?>">
		<a href="<?php echo Mage::getBaseUrl(); ?>commercial" class="level-top">
			<span><?php echo $this->__('Commercial'); ?></span>
		</a>
	</li>
	<li class="level0 nav-3 level-top parent <?php if($isIdeaPage=="0" && $route == 'wordpress') { ?> active <?php } ?>">
		<a href="<?php echo Mage::getBaseUrl(); ?>blog" class="level-top">
			<span><?php echo $this->__('Blog'); ?></span>
		</a>
	</li>
	<li class="level0 nav-4 level-top <?php if($route == 'cms' && $id == 'faq') { ?> active <?php } ?>">
		<a href="<?php echo Mage::getBaseUrl(); ?>faq" class="level-top">
			<span><?php echo $this->__('How it works'); ?></span>
		</a>
	</li>
	<li class="level0 nav-5 level-top <?php if($route == 'cms' && $id == 'about') { ?> active <?php } ?>">
		<a href="<?php echo Mage::getBaseUrl(); ?>about" class="level-top">
			<span><?php echo $this->__('About'); ?></span>
		</a>
	</li>
	<li class="level0 nav-7 last level-top <?php if($route == 'cms' && $id == 'contacts') { ?> active <?php } ?>">
		<a href="<?php echo Mage::getUrl(); ?>contacts" class="level-top">
			<span><?php echo $this->__('Contact Us'); ?></span>
		</a>
	</li>
    </ul>
	 <!--<div class="search_container"><!-- search container starts -->
	<?php if($route == 'wordpress') { ?>
	<!--<form id="blog-search-form" action="<?php echo Mage::getBaseUrl()?>blog/search/" method="get"> 
	    <div class="form-search">
                <label for="search">Search:</label>
                <input type="text" maxlength="128" class="input-text" value="" name="s" id="blog-search" autocomplete="off">
                <button class="button" title="Search" type="submit"><span><span>Search</span></span></button>
                <div class="search-autocomplete" id="search_autocomplete" style="display: none;"></div>
                <script type="text/javascript">
		//<![CDATA[
		    var wpSearchForm = Class.create(Varien.searchForm, {
			initialize : function($super, form, field, emptyText, useSeoUrls) {
			    this.useSeoUrls = useSeoUrls;
			    return $super(form, field, emptyText);
			},
			submit : function($super, event) {
			
			    if (this.useSeoUrls) {
				var o = this.form.readAttribute('action');
				var n = this.form.readAttribute('action') + encodeURIComponent(this.field.getValue().replace(' ', '-')) + '/';
				this.form.writeAttribute('action', n);
				this.field.writeAttribute('disabled', 'disabled');
				if (!$super(event)) {
				    this.form.writeAttribute('action', o);
				    this.field.writeAttribute('disabled', null);
				    Event.stop(event);
				    return false;
				}
				return true;
			    }
			    return $super(event);
			}
		    });
		    var searchForm = new wpSearchForm('blog-search-form', 'blog-search', 'Search Posts', true);
		//]]>
		</script>
            </div> 
	</form>--> 
	<?php }else{ ?> 
        <!--<form method="get" action="<?php echo Mage::getBaseUrl()?>catalogsearch/result/" id="search_mini_form">
            <div class="form-search">
                <label for="search">Search:</label>
                <input type="text" maxlength="128" class="input-text" value="" name="q" id="search" autocomplete="off">
                <button class="button" title="Search" type="submit"><span><span>Search</span></span></button>
                <div class="search-autocomplete" id="search_autocomplete" style="display: none;"></div>
                <script type="text/javascript">
                //&lt;![CDATA[
                    var searchForm = new Varien.searchForm('search_mini_form', 'search', 'Search entire store here...');
                    searchForm.initAutocomplete('http://ncolours.php-dev.in/catalogsearch/ajax/suggest/', 'search_autocomplete');
                //]]&gt;
                </script>
            </div>
        </form>-->
	
	<?php } ?>
	<!--</div><!-- search container ends -->


</div>
</div>
<?php endif ?>
