<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<?php if ($post): ?>
	<?php $helper = $this->helper('wordpress') ?>
	<?php $author = $post->getAuthor() ?>
	<?php if ($this->helper('wordpress/plugin_shareThis')->canDisplayOnPost()): ?>
		<?php echo $this->helper('wordpress/plugin_shareThis')->getJavascriptHtml() ?>
	<?php endif; ?>
	<div class="page-title post-title">
		<h1><?php //echo $this->escapeHtml($post->getPostTitle()) ?></h1>
	</div>
	<div class="post-view">
		
		<div class="post-entry entry std<?php if ($post->getFeaturedImage): ?> post-entry-with-image<?php endif; ?>">
			<?php if ($post->isViewableForVisitor()): ?>
				<?php if ($featuredImage = $post->getFeaturedImage()): ?>
					<div class="featured-image left"><img src="<?php echo $featuredImage->getAvailableImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/></div>
				<?php endif; ?>
				<div class="post-date when">
					<!--<span class="post_author"><?php echo $post->getAuthor()->getDisplayName();?></span>
					<span class="date">- <?php echo $post->getPostDate()?> </span>-->
					<div class="post_comments">
						<a href="#comments"><span><?php echo $post->getCommentCount()?></span> Comments</a>
					</div>           
			<?php //echo $this->__('This entry was posted on %s<span class=\"by-author\"> by %s</span>.', $post->getPostDate(), $post->getAuthor()->getDisplayName()) ?>
				</div>
				<div class="post-title" style="text-align: center;">
				    <h1><?php echo $this->escapeHtml($post->getPostTitle()) ?></h1>
				</div>
				<?php echo $post->getPostContent() ?>
			<?php else: ?>
				<?php echo $this->getPasswordProtectHtml() ?>
			<?php endif; ?>
		</div>
		<?php echo $this->getChildHtml('related_posts') ?>
		<?php echo $this->getMetaBlock()->setPost($post)->toHtml() ?>
		<?php if ($this->helper('wordpress/plugin_shareThis')->canDisplayOnPost()): ?>
				<div class="sharethis-icons" id="sharethis-icons-<?php echo $post->getId() ?>"><?php echo $this->helper('wordpress/plugin_shareThis')->getIcons($post) ?></div>
		<?php endif; ?>
		<?php echo $this->getCommentsHtml() ?>
	</div>
<?php endif; ?>