
<aside id="social-sidebar">
        <div class="social-navigation">
            <ul>
              <a class="s_facebook" href="https://www.facebook.com/MisterWallpaper" rel="external" target="_blank" title="Like us on Facebook" hidefocus="true" style="outline: medium none;"><li class="fb"></li></a>
              <a class="s_twitter" href="https://twitter.com/misseswallpaper" rel="external" target="_blank" title="Tweet at us on Twitter" hidefocus="true" style="outline: medium none;"><li class="twit"></li></a>                
              <a class="s_rss" href="<?php echo $this->getBaseUrl(); ?>blog" rel="external"  title="Rss" hidefocus="true" style="outline: medium none;"><li class="rss"></li></a>
              <a class="s_pin" href="http://pinterest.com/MisterWallpaper/ideas-for-feature-walls/" rel="external" target="_blank" title="Pin" hidefocus="true" style="outline: medium none;"><li class="pin"></li></a>  
              </ul>
        </div>
    </div>
</aside>
