<?php

require_once 'fotolia/fotolia-api.php';

//$api = new Fotolia_Api('5XEVph1BVGHkZz3VChlwtIHFsUW9gUMc');

$api = new Fotolia_Api('b55etmZ7eCuWnpkiTaT1cpFeGUfImwMD');

// searching for files
//$results = $api->getSearchResults(
//    array(
//        'words' => 'car',
//        'language_id' => Fotolia_Api::LANGUAGE_ID_EN_US,
//        'limit' => 1,
//    ));

//printf("Found %d results", $results['nb_results']);

//foreach ($results as $key => $value) {
    // iterating only over numeric keys and silently skip other keys
//    if (is_numeric($key)) {
       // printf("matching media ID: %d", $value['id']);
//    }
//}

// download comp file
//$comp_dl_data = $api->getMediaComp(35957426);
//$api->downloadMediaComp($comp_dl_data['url'], '/tmp/comp.jpg');

// loggin in and retrieving user data
//$api->loginUser('shankar23', 'shankar123');



//print_r($api->getUserData());
//print_r($api->getMediaGalleries());
//var_dump($api->getGalleries());
// purchasing and downloading a file
//$dl_data = $api->getMedia(35957426, 'XS');
//$api->downloadMedia($dl_data['url'], '/tmp/' . $dl_data['name']);
?>
<div>
    <ul class="display-iamges">
        <?php foreach($api->getGalleries() as $gallery): ?>
            <li>
                <div class="image">
                    <a href="javascript:selectFotoliaGallery('<?php echo $gallery['name']?>');">
                        <img class="cat-image" src="<?php echo $gallery['thumbnail_url']?>" height="100" width="100"/>
                    </a>
                </div>
                
                <div>
                    <span><?php echo "<h3>".$gallery['name']."</h3>";?></span>				
                </div>
            </li>
        <?php endforeach; ?>
</div>    
<script type="text/javascript">
    function selectFotoliaGallery(name) {
        jq("#somediv").load('<?php echo Mage::getBaseUrl()?>gallery/index/fotoliaImage/name/'+name);
    }
    
    
</script>


