<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php if ($tags = $this->getTags()): ?>
	<?php $tagCount = count($tags) ?>
	<div class="block block-blog block-blog-tag-cloud block-tags">
		<?php if ($title = $this->getTitle()): ?>
			<div class="block-title">
				<strong><span><?php echo $this->__($title) ?></span></strong>
			</div>
		<?php endif; ?>
		<div class="block-content">
			<ul class="tags-list">
				<?php $count=0;?>
				<?php foreach ($tags as $tag): ?>
					<li<?php if (--$tagCount < 1): ?> class="last"<?php endif; ?> <?php if($count==0){ ?> class="first" <?php } ?>>
						<a href="<?php echo $tag->getUrl() ?>" <?php if($count==0){ }else{ ?> class="tag<?php echo $count?> ?>" <?php } ?> ><?php echo $this->htmlEscape($tag->getName()) ?></a>
					</li>
					<?php $count++;?>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
<?php endif; ?>
<!--style="font-size:<?php echo $this->getFontSize($tag) ?>%;"-->
